[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[dev]
  publish = "dist"
  functions = "netlify/functions"
  framework = "vite"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 